image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - build
  - test
  - analyze

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker info
  - docker build -t my_flutter_app .

build_android:
  stage: build
  script:
    - docker run --rm my_flutter_app flutter build apk
  rules:
    - if: '$CI_COMMIT_BRANCH'

test_android:
  stage: test
  script:
    - docker run --rm my_flutter_app flutter test
  rules:
    - if: '$CI_COMMIT_BRANCH'

analyze_code:
  stage: analyze
  script:
    - docker run --rm my_flutter_app flutter analyze
  rules:
    - if: '$CI_COMMIT_BRANCH'
