image: docker:19.03

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375/

stages:
  - build
  - test
  - analyze

before_script:
  # Check Docker info to verify Docker is running
  - docker info

build_android:
  stage: build
  script:
    - docker build -t my_flutter_app .
    - docker run --rm my_flutter_app flutter build apk
  rules:
    - if: '$CI_COMMIT_BRANCH'

test_android:
  stage: test
  script:
    - docker run --rm my_flutter_app flutter test
  rules:
    - if: '$CI_COMMIT_BRANCH'

analyze_code:
  stage: analyze
  script:
    - docker run --rm my_flutter_app flutter analyze
  rules:
    - if: '$CI_COMMIT_BRANCH'
