image: marcom3622/food-ai:tagname

stages:
  - build
  - test
  - analyze

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - sudo docker build -t my_flutter_app .

build_android:
  stage: build
  script:
    - sudo docker run --rm my_flutter_app flutter build apk
  rules:
    - if: '$CI_COMMIT_BRANCH'

test_android:
  stage: test
  script:
    - sudo docker run --rm my_flutter_app flutter test
  rules:
    - if: '$CI_COMMIT_BRANCH'

analyze_code:
  stage: analyze
  script:
    - sudo docker run --rm my_flutter_app flutter analyze
  rules:
    - if: '$CI_COMMIT_BRANCH'
