image: marcom3622/food-ai:tagname

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .pub-cache/

stages:
  - build
  - test
  - analyze

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info
  - DOCKER_BUILDKIT=1 docker buildx build --load -t my_flutter_app .  # Ensure this is the correct context

build_android:
  stage: build
  script:
    - docker run --rm my_flutter_app flutter build apk > build_results.txt
  artifacts:
    when: always
    paths:
      - build_results.txt

test_android:
  stage: test
  script:
    - docker run --rm my_flutter_app flutter test > test_results.txt
  artifacts:
    when: always
    paths:
      - test_results.txt

analyze_code:
  stage: analyze
  script:
    - docker run --rm my_flutter_app flutter analyze > analyze_results.txt
  artifacts:
    when: always
    paths:
      - analyze_results.txt